import { Song } from "../../models/index.js"

class SongSeeder {
  static async seed() {
    const songData = [
      {
        title: "일곱 번째 감각 (The 7th Sense)",
        language: "Korean",
        albumId: "1",
        unitId: "1",
      },
      {
        title: "Without You",
        language: "Korean",
        albumId: "2",
        unitId: "1",
      },
      {
        title: "Without You (Chinese Version)",
        language: "Chinese",
        albumId: "2",
        unitId: "1",
      },
      {
        title: "Fire Truck",
        language: "Korean",
        albumId: "3",
        unitId: "2",
      },
      {
        title: "Once Again",
        language: "Korean",
        albumId: "3",
        unitId: "2",
      },
      {
        title: "Wake Up",
        language: "Korean",
        albumId: "3",
        unitId: "2",
      },
      {
        title: "Another World",
        language: "Korean",
        albumId: "3",
        unitId: "2",
      },
      {
        title: "Paradise",
        language: "Korean",
        albumId: "3",
        unitId: "2",
      },
      {
        title: "Mad City",
        language: "Korean",
        albumId: "3",
        unitId: "2",
      },
      {
        title: "Switch (feat. SR15B)",
        language: "Korean",
        albumId: "3",
        unitId: "2",
      },
      {
        title: "Chewing Gum",
        language: "Korean",
        albumId: "4",
        unitId: "3",
      },
      {
        title: "Chewing Gum (Chinese Version)",
        language: "Korean",
        albumId: "4",
        unitId: "3",
      },
      {
        title: "無限的我 (무한적아;Limitless)",
        language: "Korean",
        albumId: "5",
        unitId: "2",
      },
      {
        title: "Good Thing",
        language: "Korean",
        albumId: "5",
        unitId: "2",
      },
      {
        title: "Back 2 U(AM 01:27)",
        language: "Korean",
        albumId: "5",
        unitId: "2",
      },
      {
        title: "롤러코스터 (Heartbreaker)",
        language: "Korean",
        albumId: "5",
        unitId: "2",
      },
      {
        title: "Baby Don't Like It",
        language: "Korean",
        albumId: "5",
        unitId: "2",
      },
      {
        title: "Angel",
        language: "Korean",
        albumId: "5",
        unitId: "2",
      },
      {
        title: "마지막 첫사랑 (My First and Last)",
        language: "Korean",
        albumId: "6",
        unitId: "3",
      },
      {
        title: "最後的初戀 (My First and Last) (Chinese Version)",
        language: "Chinese",
        albumId: "6",
        unitId: "3",
      },
      {
        title: "	덩크슛(Dunk Shot)",
        language: "Korean",
        albumId: "6",
        unitId: "3",
      },
      {
        title: "Chewing Gum",
        language: "Korean",
        albumId: "6",
        unitId: "3",
      },
      {
        title: "Chewing Gum (Chinese Version)",
        language: "Chinese",
        albumId: "6",
        unitId: "3",
      },
      {
        title: "Cherry Bomb",
        language: "Korean",
        albumId: "7",
        unitId: "2",
      },
      {
        title: "Running 2 U",
        language: "Korean",
        albumId: "7",
        unitId: "2",
      },
      {
        title: "0 Mile",
        language: "Korean",
        albumId: "7",
        unitId: "2",
      },
      {
        title: "Sun & Moon",
        language: "Korean",
        albumId: "7",
        unitId: "2",
      },
      {
        title: "Whiplash",
        language: "Korean",
        albumId: "7",
        unitId: "2",
      },
      {
        title: "Summer 127",
        language: "Korean",
        albumId: "7",
        unitId: "2",
      },
      {
        title: "Cherry Bomb (Performance Version",
        language: "Korean",
        albumId: "7",
        unitId: "2",
      },
      {
        title: "We Young",
        language: "Korean",
        albumId: "8",
        unitId: "3",
      },
      {
        title: "La La Love",
        language: "Korean",
        albumId: "8",
        unitId: "3",
      },
      {
        title: "같은 시간 같은 자리 (Walk you home)",
        language: "Korean",
        albumId: "8",
        unitId: "3",
      },
      {
        title: "My Page",
        language: "Korean",
        albumId: "8",
        unitId: "3",
      },
      {
        title: "We Young (青春漾) (Chinese Version)",
        language: "Chinese",
        albumId: "8",
        unitId: "3",
      },
      {
        title: "Trigger the Fever (Bonus Track)",
        language: "Korean",
        albumId: "8",
        unitId: "3",
      },
      {
        title: "INTRO: Neo Got My Back",
        language: "English",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "BOSS",
        language: "Korean",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "Baby Don't Stop",
        language: "Korean",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "GO",
        language: "Korean",
        albumId: "9",
        unitId: "3",
      },
      {
        title: "TOUCH",
        language: "Korean",
        albumId: "9",
        unitId: "2",
      },
      {
        title: "YESTODAY",
        language: "Korean, English",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "Black On Black",
        language: "Korean, English",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "텐데… (Timeless)",
        language: "Korean",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "일곱 번째 감각 (第七感; The 7th Sense)",
        language: "Korean",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "WITHOUT YOU",
        language: "Korean",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "WITHOUT YOU (Chinese Version)",
        language: "Chinese",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "梦中梦 (몽중몽; Dream In A Dream)",
        language: "English",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "OUTRO: VISION",
        language: "Instrumental",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "YESTODAY (Extended Version) (Bonus Track)",
        language: "Korean, English",
        albumId: "9",
        unitId: "1",
      },
      {
        title: "Dreaming",
        language: "Japanese",
        albumId: "10",
        unitId: "2",
      },
      {
        title: "Chain",
        language: "Japanese",
        albumId: "10",
        unitId: "2",
      },
      {
        title: "Limitless",
        language: "Japanese",
        albumId: "10",
        unitId: "2",
      },
      {
        title: "Come Back",
        language: "Japanese",
        albumId: "10",
        unitId: "2",
      },
      {
        title: "100",
        language: "Japanese",
        albumId: "10",
        unitId: "2",
      },
      {
        title: "Baby Don't Stop (Special Thai Version",
        language: "Thai",
        albumId: "11",
        unitId: "1",
      },
      {
        title: "Baby Don't Stop (Instrumental)",
        language: "Instrumental",
        albumId: "11",
        unitId: "1",
      },
      {
        title: "We Go Up",
        language: "Korean",
        albumId: "12",
        unitId: "3",
      },
      {
        title: "1, 2, 3",
        language: "Korean",
        albumId: "12",
        unitId: "3",
      },
      {
        title: "Beautiful Time",
        language: "Korean",
        albumId: "12",
        unitId: "3",
      },
      {
        title: "Drippin'",
        language: "Korean",
        albumId: "12",
        unitId: "3",
      },
      {
        title: "Dear Dream",
        language: "Korean",
        albumId: "12",
        unitId: "3",
      },
      {
        title: "We Go Up (青春接力) (Chinese Version)",
        language: "Chinese",
        albumId: "12",
        unitId: "3",
      },
      {
        title: "Touch (Japanese Version)",
        language: "Japanese",
        albumId: "13",
        unitId: "2",
      },
      {
        title: "City 127",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "Regular (Korean Version)",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "Replay (PM 01:27)",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "Knock On",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "No Longer",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "Interlude: Regular to Irregular",
        language: "Korean, Chinese, Japanese, English",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "My Van",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "Come Back",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "Fly Away With Me",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "Regular (English Version)",
        language: "Korean, English",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "Run Back 2 U (Bonuse Track)",
        language: "Korean",
        albumId: "14",
        unitId: "2",
      },
      {
        title: "City 127",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Regular (Korean Version)",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Replay (PM 01:27)",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
       {
        title: "Welcome To My Playground",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Knock On",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "No Longer",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Interlude: Regular to Irregular",
        language: "Korean, Chinese, Japanese, English",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Simon Says",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "My Van",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Come Back",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Fly Away With Me",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Chain (Korean Version)",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Regular (English Version)",
        language: "Korean, English",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "Run Back 2 U (Bonuse Track)",
        language: "Korean",
        albumId: "15",
        unitId: "2",
      },
      {
        title: "理所当然 (Regular)",
        language: "Chinese",
        albumId: "16",
        unitId: "4",
      },
      {
        title: "噩梦 (Come Back)",
        language: "Chinese",
        albumId: "16",
        unitId: "4",
      },
      {
        title: "梦想发射计划 (Dream Launch)",
        language: "Chinese",
        albumId: "16",
        unitId: "4",
      },
      {
        title: "Lips",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Wakey-Wakey",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Chain",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Regular (English Version)",
        language: "Korean, English",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Touch (Japanese Version)",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Blow My Mind",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Limitless (Japanese Version)",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Long Slow Distance",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Kitchen Beat",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Cherry Bomb",
        language: "Korean",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "Fire Truck",
        language: "Korean",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "End to Start",
        language: "Japanese",
        albumId: "17",
        unitId: "2",
      },
      {
        title: "无翼而飞 (Take Off)",
        language: "Chinese",
        albumId: "18",
        unitId: "4",
      },
      {
        title: "理所当然 (Regular)",
        language: "Chinese",
        albumId: "18",
        unitId: "4",
      },
      {
        title: "真实谎言 (Say It)",
        language: "Chinese",
        albumId: "18",
        unitId: "4",
      },
      {
        title: "噩梦 (Come Back)",
        language: "Chinese",
        albumId: "18",
        unitId: "4",
      },
      {
        title: "爱不释手 (Let me love u)",
        language: "Chinese",
        albumId: "18",
        unitId: "4",
      },
      {
        title: "梦想发射计划 (Dream Launch)",
        language: "Chinese",
        albumId: "18",
        unitId: "4",
      },
      {
        title: "Superhuman",
        language: "Korean",
        albumId: "19",
        unitId: "2",
      },
      {
        title: "Highway to Heaven",
        language: "Korean",
        albumId: "19",
        unitId: "2",
      },
      {
        title: "FOOL",
        language: "Korean",
        albumId: "19",
        unitId: "2",
      },
      {
        title: "Jet Lag",
        language: "Korean",
        albumId: "19",
        unitId: "2",
      },
      {
        title: "Paper Plane",
        language: "Korean",
        albumId: "19",
        unitId: "2",
      },
      {
        title: "OUTRO : WE ARE 127",
        language: "Korean",
        albumId: "19",
        unitId: "2",
      },
      {
        title: "Fireflies (THE OFFICIAL SONG OF THE WORLD SCOUT FOUNDATION)",
        language: "English",
        albumId: "20",
        unitId: "3",
      },
      {
        title: "Highway To Heaven (English Version)",
        language: "English",
        albumId: "21",
        unitId: "2",
      },
      {
        title: "BOOM",
        language: "Korean",
        albumId: "22",
        unitId: "3",
      },
      {
        title: "STRONGER",
        language: "Korean",
        albumId: "22",
        unitId: "3",
      },
      {
        title: "119",
        language: "Korean",
        albumId: "22",
        unitId: "3",
      },
      {
        title: "Bye My First...",
        language: "Korean",
        albumId: "22",
        unitId: "3",
      },
      {
        title: "Best Friend",
        language: "Korean",
        albumId: "22",
        unitId: "3",
      },
      {
        title: "Dream Run",
        language: "Korean",
        albumId: "22",
        unitId: "3",
      },
      {
        title: "天选之城 (Moonwalk)",
        language: "Chinese",
        albumId: "23",
        unitId: "4",
      },
      {
        title: "黑夜日出 (Yeah Yeah Yeah)",
        language: "Chinese",
        albumId: "23",
        unitId: "4",
      },
      {
        title: "秘语 (Love Talk)",
        language: "Chinese",
        albumId: "23",
        unitId: "4",
      },
      {
        title: "心心相瘾 (King of Hearts)",
        language: "Chinese",
        albumId: "23",
        unitId: "4",
      },
      {
        title: "面对面 (Face to Face)",
        language: "Chinese",
        albumId: "23",
        unitId: "4",
      },
      {
        title: "幸福遇见 (We go nanana)",
        language: "Chinese",
        albumId: "23",
        unitId: "4",
      },
      {
        title: "Love Talk (English Version)",
        language: "English",
        albumId: "24",
        unitId: "4",
      },
      {
        title: "Elevator (127F)",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Kick It",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Boom",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Pandora's Box",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Day Dream",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Interlude: Neo Zone",
        language: "Instrumental",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "MAD DOG",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Sit Down!",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Love Me Now",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Love Song",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "White Night",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Not Alone",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Dreams Come True",
        language: "Korean",
        albumId: "25",
        unitId: "2",
      },
      {
        title: "Ridin'",
        language: "Korean",
        albumId: "26",
        unitId: "3",
      },
      {
        title: "Quiet Down",
        language: "Korean",
        albumId: "26",
        unitId: "3",
      },
      {
        title: "7 Days",
        language: "Korean",
        albumId: "26",
        unitId: "3",
      },
      {
        title: "Love Again",
        language: "Korean",
        albumId: "26",
        unitId: "3",
      },
      {
        title: "Puzzle Piece",
        language: "Korean",
        albumId: "26",
        unitId: "3",
      },
      {
        title: "Punch",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Nonstop",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Prelude",
        language: "Instrumental",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Kick It",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Boom",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Pandora's Box",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Day Dream",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Make Your Day",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Interlude: Neo Zone",
        language: "Instrumental",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "MAD DOG",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Sit Down!",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Love Me Now",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Love Song",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "White Night",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Not Alone",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Dreams Come True",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "Elevator (127F)",
        language: "Korean",
        albumId: "27",
        unitId: "2",
      },
      {
        title: "超越时空 (Turn Back Time)",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "Bad Alive",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "执迷 (Unbreakable)",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "After Midnight",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "Interlude: Awaken the World",
        language: "Instrumental",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "Only Human",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "多米诺 (Domino)",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "浪漫发酵 (Up from Here)",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "Electric Hearts",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "Stand by Me",
        language: "Chinese",
        albumId: "28",
        unitId: "4",
      },
      {
        title: "Turn Back Time (Korean Version",
        language: "Korean",
        albumId: "29",
        unitId: "4",
      },
      {
        title: "Bad Alive (English Version)",
        language: "Korean, Chinese, English",
        albumId: "30",
        unitId: "4",
      },
      {
        title: "Make A Wish (Birthday Song)",
        language: "Korean",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "Misfit",
        language: "Korean",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "Volcano",
        language: "Korean",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "백열등 (Light Bulb)",
        language: "Korean",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "Dancing In The Rain",
        language: "Korean",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "Interlude: Past to Present",
        language: "Instrumental",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "무대로 (Déjà Vu; 舞代路)",
        language: "Korean",
        albumId: "31",
        unitId: "3",
      },
      {
        title: "月之迷 (Nectar)",
        language: "Chinese",
        albumId: "31",
        unitId: "4",
      },
      {
        title: "Music, Dance",
        language: "Korean",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "피아노 (Faded In My Last Song)",
        language: "Korean",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "From Home",
        language: "Korean, Chinese, Japanese",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "From Home (Korean Version)",
        language: "Korean",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "Make A Wish (Birthday Song) (English Version)",
        language: "English",
        albumId: "31",
        unitId: "1",
      },
      {
        title: "90's Love",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Misfit",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Raise the Roof",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Volcano",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "백열등 (Light Bulb)",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Dancing In The Rain",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "My Everything",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Interlude: Past to Present",
        language: "Instrumental",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Make A Wish (Birthday Song)",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "무대로 (Déjà Vu; 舞代路)",
        language: "Korean",
        albumId: "32",
        unitId: "3",
      },
      {
        title: "月之迷 (Nectar)",
        language: "Chinese",
        albumId: "32",
        unitId: "4",
      },
      {
        title: "Music, Dance",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "피아노 (Faded In My Last Song)",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "From Home",
        language: "Korean, Chinese, Japanese",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "From Home (Korean Version)",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Make A Wish (Birthday Song) (English Version)",
        language: "English",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Interlude: Present to Future",
        language: "Instrumental",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Work It",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "All About You",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "I.O.U",
        language: "Korean",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "Outro: Dream Routine",
        language: "Instrumental",
        albumId: "32",
        unitId: "1",
      },
      {
        title: "RESONANCE",
        language: "Korean",
        albumId: "33",
        unitId: "1",
      },
      {
        title: "gimme gimme",
        language: "Japanese",
        albumId: "34",
        unitId: "2",
      },
      {
        title: "Lipstick",
        language: "Japanese",
        albumId: "34",
        unitId: "2",
      },
      {
        title: "First Love",
        language: "Japanese",
        albumId: "34",
        unitId: "2",
      },
      {
        title: "Chica Bom Bom",
        language: "Japanese",
        albumId: "34",
        unitId: "2",
      },
      {
        title: "英雄; Kick It",
        language: "Korean",
        albumId: "34",
        unitId: "2",
      },
      {
        title: "Right Now",
        language: "Japanese",
        albumId: "34",
        unitId: "2",
      },
      {
        title: "秘境 (Kick Back)",
        language: "Chinese",
        albumId: "35",
        unitId: "4",
      },
      {
        title: "Action Figure",
        language: "Chinese",
        albumId: "35",
        unitId: "4",
      },
      {
        title: "天空海 (Horizon)",
        language: "Chinese",
        albumId: "35",
        unitId: "4",
      },
      {
        title: "梦尽 (All for Love)",
        language: "Chinese",
        albumId: "35",
        unitId: "4",
      },
      {
        title: "Good Time",
        language: "Chinese",
        albumId: "35",
        unitId: "4",
      },
      {
        title: "Kick Back (Korean Version)",
        language: "Korean",
        albumId: "35",
        unitId: "4",
      },
      {
        title: "맛 (Hot Sauce)",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "Diggity",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "Dive Into You",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "My Youth",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "Rocket",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "Countdown (3, 2, 1)",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "ANL",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "Irreplaceable",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "Be There For You",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "Rainbow",
        language: "Korean",
        albumId: "36",
        unitId: "3",
      },
      {
        title: "这时烟火 (Back To You)",
        language: "Chinese",
        albumId: "37",
        unitId: "4",
      },
      {
        title: "夜未眠 (Sleepless)",
        language: "Chinese",
        albumId: "37",
        unitId: "4",
      },
      {
        title: "这时烟火 (Back To You) (English Version)",
        language: "Chinese",
        albumId: "37",
        unitId: "4",
      },
      {
        title: "Hello Future",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Bungee",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "맛 (Hot Sauce)",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Life Is Still Going On",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Diggity",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Dive Into You",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "My Youth",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Rocket",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Countdown (3, 2, 1)",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "ANL",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Irreplaceable",
        language: "Korean",
        albumId: "3",
        unitId: "3",
      },
      {
        title: "Be There For You",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Rainbow",
        language: "Korean",
        albumId: "38",
        unitId: "3",
      },
      {
        title: "Low Low",
        language: "English",
        albumId: "39",
        unitId: "4",
      },
      {
        title: "Sticker",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "Lemonade",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "Breakfast",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "같은 시선 (Focus)",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "내일의 나에게 (The Rainy Night)",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "Far",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "Bring the Noize",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "Magic Carpet Ride",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "Road Trip",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "Dreamer",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "다시 만나는 날 (Promise You)",
        language: "Korean",
        albumId: "40",
        unitId: "2",
      },
      {
        title: "Favorite (Vampire)",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Sticker",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Love On The Floor",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Lemonade",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Breakfast",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Pilot",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "같은 시선 (Focus)",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "내일의 나에게 (The Rainy Night)",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Far",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Bring the Noize",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Magic Carpet Ride",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Road Trip",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Dreamer",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "다시 만나는 날 (Promise You)",
        language: "Korean",
        albumId: "41",
        unitId: "2",
      },
      {
        title: "Universe (Let's Play Ball)",
        language: "Korean",
        albumId: "42",
        unitId: "1",
      },
      {
        title: "New Axis",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Universe (Let's Play Ball)",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Earthquake",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "OK!",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Birthday Party",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Know Now",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Dreaming",
        language: "Korean",
        albumId: "43",
        unitId: "3",
      },
      {
        title: "Round&Round",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Miracle",
        language: "English",
        albumId: "43",
        unitId: "4",
      },
      {
        title: "Vroom",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Sweet Dream",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "별자리 (Good Night)",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Beautiful",
        language: "Korean",
        albumId: "43",
        unitId: "1",
      },
      {
        title: "Fire Alarm",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "별자리 (Good Night)",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "Arcade",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "너를 위한 단어 (It's Yours)",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "잘자 (Teddy Bear)",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "내일 봐 (Replay)",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "Saturday Drip",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "지금 (Better Than Gold)",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "미니카 (Drive)",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "북극성 (Never Goodbye)",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "Rewind",
        language: "Korean",
        albumId: "44",
        unitId: "3",
      },
      {
        title: "Beatbox",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "Fire Alarm",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "별자리 (Good Night)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "Arcade",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "마지막 인사 (To My First)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "너를 위한 단어 (It's Yours)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "잘자 (Teddy Bear)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "Sorry, Heart",
        language: "Korean, English",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "내일 봐 (Replay)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "Saturday Drip",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "지금 (Better Than Gold)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "미니카 (Drive)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "북극성 (Never Goodbye)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "Rewind",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "별 밤 (On the way)",
        language: "Korean",
        albumId: "45",
        unitId: "3",
      },
      {
        title: "Faster",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "질주 (2 Baddies)",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "Time Lapse",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "불시착 (Crash Landing)",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "Designer",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "윤슬 (Gold Dust)",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "흑백 영화 (Black Clouds)",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "Playback",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "Tasty (貘)",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "Vitamin",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "LOL (Laugh-Out-Loud)",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "1, 2, 7 (Time Stops)",
        language: "Korean",
        albumId: "46",
        unitId: "2",
      },
      {
        title: "Candy",
        language: "Korean",
        albumId: "47",
        unitId: "3",
      },
      {
        title: "Graduation",
        language: "Korean",
        albumId: "47",
        unitId: "3",
      },
      {
        title: "Tangerine Love (Favorite)",
        language: "Korean",
        albumId: "47",
        unitId: "3",
      },
      {
        title: "입김 (Take My Breath)",
        language: "Korean",
        albumId: "47",
        unitId: "3",
      },
      {
        title: "문 (Moon)",
        language: "Korean",
        albumId: "47",
        unitId: "3",
      },
      {
        title: "발자국 (Walk With You)",
        language: "Korean",
        albumId: "47",
        unitId: "3",
      },
      {
        title: "Phantom",
        language: "Chinese",
        albumId: "48",
        unitId: "4",
      },
      {
        title: "Diamonds Only",
        language: "Chinese",
        albumId: "48",
        unitId: "4",
      },
      {
        title: "Good Life",
        language: "Chinese",
        albumId: "48",
        unitId: "4",
      },
      {
        title: "时间拼图 (Broken Love)",
        language: "Chinese",
        albumId: "48",
        unitId: "4",
      },
      {
        title: "Bounce Back",
        language: "Chinese",
        albumId: "48",
        unitId: "4",
      },
      {
        title: "Try My Luck",
        language: "Chinese",
        albumId: "48",
        unitId: "4",
      },
      {
        title: "这时烟火 (Back To You) (Bonus Track)",
        language: "Chinese",
        albumId: "48",
        unitId: "4",
      },
      {
        title: "Low Low (Bonus Track)",
        language: "English",
        albumId: "48",
        unitId: "4",
      },
      {
        title: "Ay-Yo",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "Faster",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "질주 (2 Baddies)",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "Time Lapse",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "DJ",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "불시착 (Crash Landing)",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "Designer",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "윤슬 (Gold Dust)",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "흑백 영화 (Black Clouds)",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "Playback",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "摩天樓; 마천루 (Skyscraper)",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "Tasty (貘)",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "Vitamin",
        language: "Korean",
        albumId: "49",
        unitId: "2"
      },
      {
        title: "LOL (Laugh-Out-Loud)",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "1, 2, 7 (Time Stops)",
        language: "Korean",
        albumId: "49",
        unitId: "2",
      },
      {
        title: "Best Friend Ever",
        language: "Japanese",
        albumId: "50",
        unitId: "3",
      },
      {
        title: "Glitch Mode (Japanese ver.)",
        language: "Japanese",
        albumId: "50",
        unitId: "3",
      },
    ]
    for (const singleSongData of songData) {
      const currentSong = await Song.query().findOne(singleSongData)
      if (!currentSong) {
        await Song.query().insert(singleSongData)
      }
    }
  }
}

export default SongSeeder